name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH Private Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          script: |
            cd ~/var/www/sigma
            git pull origin main
            npm install
            npm run build
            pm2 restart sigma # If you use PM2 for process management
