name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY_PASSPHRASE" > passphrase.txt
          echo "$SSH_PRIVATE_KEY" > private_key.txt
          chmod 600 private_key.txt
          ssh-keygen -p -P "$(cat passphrase.txt)" -N "" -f private_key.txt

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            ${{ secrets.SSH_PRIVATE_KEY }}
            -----END RSA PRIVATE KEY-----
          script: |
            cd ~/var/www/sigma
            git pull origin main
            npm install
            npm run build
            pm2 restart sigma # If you use PM2 for process management

